DELETE FROM FACILITY
DELETE FROM FACILITY_SPORTMODALITY
DELETE FROM LESSON
DELETE FROM LESSON_DAYS_OF_WEEK
DELETE FROM OCCUPATION
DELETE FROM REGISTRATION
DELETE FROM SPORTMODALITY
DELETE FROM USER

INSERT INTO SPORTMODALITY (ID, NAME, MINDURATION, COSTPERHOUR) VALUES (1,'Pilates', 50, 7)
INSERT INTO SPORTMODALITY (ID, NAME, MINDURATION, COSTPERHOUR) VALUES (2, 'Step', 45, 10)
INSERT INTO SPORTMODALITY (ID, NAME, MINDURATION, COSTPERHOUR) VALUES (3, 'GAP', 50, 10)
INSERT INTO SPORTMODALITY (ID, NAME, MINDURATION, COSTPERHOUR) VALUES (4, 'Indoor Cycling', 55, 10)
INSERT INTO SPORTMODALITY (ID, NAME, MINDURATION, COSTPERHOUR) VALUES (5, 'Hidroginastica', 45, 15)

INSERT INTO FACILITY (ID, NAME, MAXCAPACITY, FACILITYTYPE) VALUES (1, 'Estudio 1', 20, 'ESTUDIO')
INSERT INTO FACILITY (ID, NAME, MAXCAPACITY, FACILITYTYPE) VALUES (2, 'Estudio 2', 15, 'ESTUDIO')
INSERT INTO FACILITY (ID, NAME, MAXCAPACITY, FACILITYTYPE) VALUES (3, 'Biclas', 10, 'SALA_DE_BICICLETAS')
INSERT INTO FACILITY (ID, NAME, MAXCAPACITY, FACILITYTYPE) VALUES (4, 'Piscina 25', 20, 'PISCINA')

INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (1, 1)
INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (1, 2)
INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (1, 3)
INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (2, 1)
INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (3, 4)
INSERT INTO FACILITY_SPORTMODALITY (FACILITY_ID, SPORTMODALITIES_ID) VALUES (4, 5)

INSERT INTO USER (ID, USERID, NAME, NIF) VALUES (1, 1, 'Ulisses', 223842389)
INSERT INTO USER (ID, USERID, NAME, NIF) VALUES (2, 2, 'David', 256039682)
INSERT INTO USER (ID, USERID, NAME, NIF) VALUES (3, 3, 'Teresa', 269901841)
INSERT INTO USER (ID, USERID, NAME, NIF) VALUES (4, 4, 'Querubim', 197672337)
INSERT INTO USER (ID, USERID, NAME, NIF) VALUES (5, 5, 'C�cero', 221057552)
