package business.sportModality.exceptions;

public class SportModalityNotFoundException extends Exception {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = -5542059007964249029L;

    public SportModalityNotFoundException(String message) {
        super(message);
    }


    /**
     * Creates an exception wrapping a lower level exception.
     *
     * @param message The error message
     * @param e       The wrapped exception.
     */
    public SportModalityNotFoundException(String message, Exception e) {
        super(message, e);
    }


}
